[package]
name = "erc20-topup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
dotenv = "0.15.0"
ethers = "2.0.10"
eyre = "0.6.8"
futures = "0.3.28"
hex = "0.4.3"
rand = "0.8.5"
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
reqwest = "0.11.20"
serde = "1.0.188"
tokio = { version = "1.32.0", features = ["full"] }
