[package]
name = "erc20-topup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
ethers = "2.0.10"
eyre = "0.6.8"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["full"] }
