[package]
name = "erc20-topup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
dotenv = "0.15.0"
ethers = "2.0.14"
eyre = "0.6.12"
futures = "0.3.28"
hex = "0.4.3"
rand = "0.8.5"
serde_json = "1.0.108"
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
serde = "1.0.188"
tokio = { version = "1.32.0", features = ["full"] }
