name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  ETH_RPC_URL: https://eth.drpc.org

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: foundryup
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          /home/runner/.config/.foundry/bin/foundryup
      - name: Update
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: |
            export PATH="$PATH:/home/runner/.config/.foundry/bin"
            cargo test --verbose -- --nocapture
      - name: Run Clippy
        run: cargo clippy